# Generated by Django 5.2.7 on 2025-11-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoicepdfrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
