# Generated by Django 5.2.7 on 2025-11-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_gst_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('weight', 'By Weight'), ('count', 'By Count')], default='weight', max_length=10),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='sweet_type',
            field=models.CharField(choices=[('weight', 'By Weight'), ('count', 'By Count')], default='weight', max_length=10),
        ),
    ]
