# Generated by Django 5.2.7 on 2025-11-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoiceitem_item_type_alter_sweet_sweet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/%d/'),
        ),
    ]
