# Generated by Django 5.2.7 on 2025-11-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoice_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sweet',
            options={'ordering': ['-usage_count', '-last_used', 'name']},
        ),
        migrations.AddField(
            model_name='sweet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sweet',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sweet',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
