# Generated by Django 5.2.7 on 2025-11-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_sweet_options_sweet_created_at_sweet_last_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='sweet_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='sweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.sweet'),
        ),
    ]
