# Generated by Django 5.2.7 on 2025-11-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_productmaster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
